export const config = {
    NODE_ENV: "NODE_ENV",
    PANEL_PORT: "PANEL_PORT",
    CLD_CLOUD_NAME: "CLD_CLOUD_NAME",
    CLD_API_KEY: "CLD_API_KEY",
    CLD_API_SECRET: "CLD_API_SECRET",
    GATEWAY_MONGODB_URL: "GATEWAY_MONGODB_URL",
    AD_SECRET_KEY: "AD_SECRET_KEY",
    AD_JWT_TOKEN_EXPIRY_TIME: "AD_JWT_TOKEN_EXPIRY_TIME",
};
